export const DEFAULT_REFERRAL_CREDITS = 10;
export const REFERRAL_CODE_LENGTH = 8;
export const REFERRAL_CODE_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
export const REFERRAL_LINK_BASE = process.env.NEXT_PUBLIC_APP_URL;
